/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CvIndexRouteImport } from './routes/cv/index'
import { Route as CvCompanyRouteImport } from './routes/cv/$company'

const CvIndexRoute = CvIndexRouteImport.update({
  id: '/cv/',
  path: '/cv/',
  getParentRoute: () => rootRouteImport,
} as any)
const CvCompanyRoute = CvCompanyRouteImport.update({
  id: '/cv/$company',
  path: '/cv/$company',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/cv/$company': typeof CvCompanyRoute
  '/cv': typeof CvIndexRoute
}
export interface FileRoutesByTo {
  '/cv/$company': typeof CvCompanyRoute
  '/cv': typeof CvIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/cv/$company': typeof CvCompanyRoute
  '/cv/': typeof CvIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/cv/$company' | '/cv'
  fileRoutesByTo: FileRoutesByTo
  to: '/cv/$company' | '/cv'
  id: '__root__' | '/cv/$company' | '/cv/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CvCompanyRoute: typeof CvCompanyRoute
  CvIndexRoute: typeof CvIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cv/': {
      id: '/cv/'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv/$company': {
      id: '/cv/$company'
      path: '/cv/$company'
      fullPath: '/cv/$company'
      preLoaderRoute: typeof CvCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CvCompanyRoute: CvCompanyRoute,
  CvIndexRoute: CvIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
