/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CvRouteImport } from './routes/cv'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CvCompanyRouteImport } from './routes/cv/$company'

const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CvCompanyRoute = CvCompanyRouteImport.update({
  id: '/$company',
  path: '/$company',
  getParentRoute: () => CvRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cv': typeof CvRouteWithChildren
  '/cv/$company': typeof CvCompanyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cv': typeof CvRouteWithChildren
  '/cv/$company': typeof CvCompanyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cv': typeof CvRouteWithChildren
  '/cv/$company': typeof CvCompanyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cv' | '/cv/$company'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cv' | '/cv/$company'
  id: '__root__' | '/' | '/cv' | '/cv/$company'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CvRoute: typeof CvRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv/$company': {
      id: '/cv/$company'
      path: '/$company'
      fullPath: '/cv/$company'
      preLoaderRoute: typeof CvCompanyRouteImport
      parentRoute: typeof CvRoute
    }
  }
}

interface CvRouteChildren {
  CvCompanyRoute: typeof CvCompanyRoute
}

const CvRouteChildren: CvRouteChildren = {
  CvCompanyRoute: CvCompanyRoute,
}

const CvRouteWithChildren = CvRoute._addFileChildren(CvRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CvRoute: CvRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
