// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {})
}

/**
 * Award
 */
export type Award = {
  /**
   * Title
   */
  title: string
  /**
   * Date
   */
  date?: string | null
  /**
   * Awarder
   */
  awarder?: string | null
  /**
   * Summary
   */
  summary?: string | null
}

/**
 * Basics
 */
export type Basics = {
  /**
   * Name
   */
  name: string
  /**
   * Label
   */
  label?: string | null
  /**
   * Image
   */
  image?: string | null
  /**
   * Email
   */
  email?: string | null
  /**
   * Phone
   */
  phone?: string | null
  /**
   * Url
   */
  url?: string | null
  /**
   * Summary
   */
  summary?: string | null
  /**
   * Future
   */
  future?: string | null
  location?: Location | null
  /**
   * Profiles
   */
  profiles?: Array<Profile> | null
}

/**
 * CV
 *
 * Full CV matching JSON CV schema
 */
export type CvInput = {
  basics: Basics
  /**
   * Work
   */
  work?: Array<Work> | null
  /**
   * Volunteer
   */
  volunteer?: Array<Volunteer> | null
  /**
   * Education
   */
  education?: Array<Education> | null
  /**
   * Awards
   */
  awards?: Array<Award> | null
  /**
   * Certificates
   */
  certificates?: Array<Certificate> | null
  /**
   * Publications
   */
  publications?: Array<Publication> | null
  /**
   * Skills
   */
  skills?: Array<Skill> | null
  /**
   * Languages
   */
  languages?: Array<Language> | null
  /**
   * Interests
   */
  interests?: Array<Interest> | null
  /**
   * References
   */
  references?: Array<Reference> | null
  /**
   * Projects
   */
  projects?: Array<Project> | null
}

/**
 * CV
 *
 * Full CV matching JSON CV schema
 */
export type CvOutput = {
  basics: Basics
  /**
   * Work
   */
  work?: Array<Work> | null
  /**
   * Volunteer
   */
  volunteer?: Array<Volunteer> | null
  /**
   * Education
   */
  education?: Array<Education> | null
  /**
   * Awards
   */
  awards?: Array<Award> | null
  /**
   * Certificates
   */
  certificates?: Array<Certificate> | null
  /**
   * Publications
   */
  publications?: Array<Publication> | null
  /**
   * Skills
   */
  skills?: Array<Skill> | null
  /**
   * Languages
   */
  languages?: Array<Language> | null
  /**
   * Interests
   */
  interests?: Array<Interest> | null
  /**
   * References
   */
  references?: Array<Reference> | null
  /**
   * Projects
   */
  projects?: Array<Project> | null
}

/**
 * CVCreate
 *
 * Request to create a new CV
 */
export type CvCreate = {
  /**
   * Type
   */
  type: string
  /**
   * Name
   */
  name: string
  content: CvInput
  /**
   * Parent Id
   */
  parent_id?: string | null
  /**
   * Job Id
   */
  job_id?: string | null
  /**
   * Role Id
   */
  role_id?: string | null
  /**
   * Company Id
   */
  company_id?: string | null
}

/**
 * CVResponse
 *
 * CV response with metadata
 */
export type CvResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Type
   */
  type: string
  /**
   * Name
   */
  name: string
  /**
   * Parent Id
   */
  parent_id?: string | null
  /**
   * Job Id
   */
  job_id?: string | null
  /**
   * Role Id
   */
  role_id?: string | null
  /**
   * Company Id
   */
  company_id?: string | null
  content: CvOutput
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
}

/**
 * CVUpdate
 *
 * Request to update a CV
 */
export type CvUpdate = {
  /**
   * Name
   */
  name?: string | null
  content?: CvInput | null
}

/**
 * Certificate
 */
export type Certificate = {
  /**
   * Name
   */
  name: string
  /**
   * Date
   */
  date?: string | null
  /**
   * Issuer
   */
  issuer?: string | null
  /**
   * Url
   */
  url?: string | null
}

/**
 * Education
 */
export type Education = {
  /**
   * Institution
   */
  institution: string
  /**
   * Url
   */
  url?: string | null
  /**
   * Area
   */
  area?: string | null
  /**
   * Studytype
   */
  studyType?: string | null
  /**
   * Startdate
   */
  startDate?: string | null
  /**
   * Enddate
   */
  endDate?: string | null
  /**
   * Score
   */
  score?: string | null
  /**
   * Courses
   */
  courses?: Array<string> | null
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * Interest
 */
export type Interest = {
  /**
   * Name
   */
  name: string
  /**
   * Keywords
   */
  keywords?: Array<string> | null
}

/**
 * Language
 */
export type Language = {
  /**
   * Language
   */
  language: string
  /**
   * Fluency
   */
  fluency?: string | null
}

/**
 * Location
 */
export type Location = {
  /**
   * Address
   */
  address?: string | null
  /**
   * Postalcode
   */
  postalCode?: string | null
  /**
   * City
   */
  city?: string | null
  /**
   * Countrycode
   */
  countryCode?: string | null
  /**
   * Region
   */
  region?: string | null
}

/**
 * Profile
 */
export type Profile = {
  /**
   * Network
   */
  network: string
  /**
   * Username
   */
  username?: string | null
  /**
   * Url
   */
  url?: string | null
}

/**
 * Project
 */
export type Project = {
  /**
   * Name
   */
  name: string
  /**
   * Startdate
   */
  startDate?: string | null
  /**
   * Enddate
   */
  endDate?: string | null
  /**
   * Description
   */
  description?: string | null
  /**
   * Highlights
   */
  highlights?: Array<string> | null
  /**
   * Url
   */
  url?: string | null
  /**
   * Keywords
   */
  keywords?: Array<string> | null
}

/**
 * Publication
 */
export type Publication = {
  /**
   * Name
   */
  name: string
  /**
   * Publisher
   */
  publisher?: string | null
  /**
   * Releasedate
   */
  releaseDate?: string | null
  /**
   * Url
   */
  url?: string | null
  /**
   * Summary
   */
  summary?: string | null
}

/**
 * Reference
 */
export type Reference = {
  /**
   * Name
   */
  name: string
  /**
   * Reference
   */
  reference?: string | null
}

/**
 * Skill
 */
export type Skill = {
  /**
   * Name
   */
  name: string
  /**
   * Level
   */
  level?: string | null
  /**
   * Keywords
   */
  keywords?: Array<string> | null
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
}

/**
 * Volunteer
 */
export type Volunteer = {
  /**
   * Organization
   */
  organization: string
  /**
   * Position
   */
  position?: string | null
  /**
   * Url
   */
  url?: string | null
  /**
   * Startdate
   */
  startDate?: string | null
  /**
   * Enddate
   */
  endDate?: string | null
  /**
   * Summary
   */
  summary?: string | null
  /**
   * Highlights
   */
  highlights?: Array<string> | null
}

/**
 * Work
 */
export type Work = {
  /**
   * Name
   */
  name?: string | null
  /**
   * Position
   */
  position?: string | null
  /**
   * Url
   */
  url?: string | null
  /**
   * Location
   */
  location?: string | null
  /**
   * Slug
   */
  slug?: string | null
  /**
   * Startdate
   */
  startDate?: string | null
  /**
   * Enddate
   */
  endDate?: string | null
  /**
   * Summary
   */
  summary?: string | null
  /**
   * Highlights
   */
  highlights?: Array<string> | null
}

export type ListCvsData = {
  body?: never
  path?: never
  query?: never
  url: '/cv/'
}

export type ListCvsResponses = {
  /**
   * Response Listcvs
   *
   * Successful Response
   */
  200: Array<CvResponse>
}

export type ListCvsResponse = ListCvsResponses[keyof ListCvsResponses]

export type CreateCvData = {
  body: CvCreate
  path?: never
  query?: never
  url: '/cv/'
}

export type CreateCvErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateCvError = CreateCvErrors[keyof CreateCvErrors]

export type CreateCvResponses = {
  /**
   * Successful Response
   */
  201: CvResponse
}

export type CreateCvResponse = CreateCvResponses[keyof CreateCvResponses]

export type DeleteCvData = {
  body?: never
  path: {
    /**
     * Cv Id
     */
    cv_id: string
  }
  query?: never
  url: '/cv/{cv_id}'
}

export type DeleteCvErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteCvError = DeleteCvErrors[keyof DeleteCvErrors]

export type DeleteCvResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type DeleteCvResponse = DeleteCvResponses[keyof DeleteCvResponses]

export type GetCvData = {
  body?: never
  path: {
    /**
     * Cv Id
     */
    cv_id: string
  }
  query?: never
  url: '/cv/{cv_id}'
}

export type GetCvErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetCvError = GetCvErrors[keyof GetCvErrors]

export type GetCvResponses = {
  /**
   * Successful Response
   */
  200: CvResponse
}

export type GetCvResponse = GetCvResponses[keyof GetCvResponses]

export type UpdateCvData = {
  body: CvUpdate
  path: {
    /**
     * Cv Id
     */
    cv_id: string
  }
  query?: never
  url: '/cv/{cv_id}'
}

export type UpdateCvErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateCvError = UpdateCvErrors[keyof UpdateCvErrors]

export type UpdateCvResponses = {
  /**
   * Successful Response
   */
  200: CvResponse
}

export type UpdateCvResponse = UpdateCvResponses[keyof UpdateCvResponses]

export type HealthData = {
  body?: never
  path?: never
  query?: never
  url: '/health'
}

export type HealthResponses = {
  /**
   * Successful Response
   */
  200: unknown
}
